### ISSUE TITLE
Randomly select 100 mutants for Qual Tag Validation

### ISSUE THREAD

**Issue by bkushigian** [bkushigian/cornelius-eval-data#13]

**Comment by bkushigian** [comment]
@ryanfeatherman Can you add your design choices/implementation details here?

**Comment by ryanfeatherman** [comment]
Implementation was to order tags by frequency. I then iterated through, incrementing each tag's number of samples if we haven't exceeded the number in that category until we reach SAMPLE_SIZE (100). This means that the k "leftover" samples that can't be even dispersed are given to the k most populated tags.

**Comment by ryanfeatherman** [comment]
Results are in qualitative/validate/sample.py
